# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

build: off

cache:
  - vendor/bundle

install:
  - set PATH=C:\Ruby24-x64\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

test_script:
  - bundle exec rake spec
  - C:/Ruby24-x64/bin/ruby.exe -S pact verify --pact-helper ./provider/spec/pact_helper.rb --pact-uri ./consumer/spec/pacts/foo-bar.json
